#!/bin/bash

# Screenshot Generation Script for Currywort
# This script helps you create the required App Store screenshots

echo "📱 Currywort App Store Screenshot Generator"
echo "=========================================="
echo ""

echo "Required iPhone Screenshots:"
echo "• iPhone 6.7\" (iPhone 15 Pro Max): 1290 x 2796 pixels"
echo "• iPhone 6.5\" (iPhone 14 Plus): 1284 x 2778 pixels" 
echo "• iPhone 5.5\" (iPhone 8 Plus): 1242 x 2208 pixels"
echo ""

echo "📋 Screenshot Content Suggestions:"
echo ""
echo "1. Main Learning Screen:"
echo "   - Show a German word card"
echo "   - Display the progress indicators"
echo "   - Show the swipe instructions"
echo ""
echo "2. Card Back View:"
echo "   - Show English translation"
echo "   - Display example sentences"
echo "   - Show the bucket indicator"
echo ""
echo "3. Progress Screen:"
echo "   - Show the circular progress indicator"
echo "   - Display bucket counts"
echo "   - Show overall progress"
echo ""
echo "4. Edit Modal:"
echo "   - Show the edit interface"
echo "   - Display personal notes feature"
echo ""
echo "5. Dark Mode:"
echo "   - Show the app in dark theme"
echo "   - Highlight the visual design"
echo ""

echo "🎨 Screenshot Tips:"
echo "• Use real content, not placeholder text"
echo "• Show different German words in each screenshot"
echo "• Include the app's visual indicators (progress, buckets)"
echo "• Use both light and dark modes"
echo "• Make sure text is readable"
echo "• Show the app's key features"
echo ""

echo "📱 How to Take Screenshots:"
echo "1. Run the app in iOS Simulator"
echo "2. Use Device → Screenshot in Simulator menu"
echo "3. Or use Cmd+S keyboard shortcut"
echo "4. Save with descriptive names:"
echo "   - currywort-main-screen-6.7.png"
echo "   - currywort-card-back-6.5.png"
echo "   - currywort-progress-5.5.png"
echo ""

echo "🚀 Next Steps:"
echo "1. Take screenshots using iOS Simulator"
echo "2. Resize to required dimensions if needed"
echo "3. Upload to App Store Connect"
echo "4. Follow SUBMISSION_CHECKLIST.md"
echo ""

echo "💡 Pro Tip:"
echo "Take screenshots in both light and dark modes to show"
echo "the app's visual appeal and attention to detail!"
